using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Arma3.DllExport.MsBuild")]
[assembly: AssemblyCompanyAttribute("Maca134")]
[assembly: AssemblyProductAttribute("Arma3.DllExport.MsBuild")]
[assembly: AssemblyCopyrightAttribute("Copyright 2017")]
[assembly: AssemblyVersionAttribute("0.0.2.7")]
[assembly: AssemblyFileVersionAttribute("0.0.2.7")]

