using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Arma3.DllExport")]
[assembly: AssemblyCompany("Ni1kko")]
[assembly: AssemblyProductAttribute("Arma3.DllExport")]
[assembly: AssemblyCopyright("Copyright 2025")]
[assembly: AssemblyVersion("0.1.0.6")]
[assembly: AssemblyFileVersion("0.1.0.6")]

